name: pre-commit-lint

on:
  pull_request:
    branches:
    - master
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - uses: actions/setup-go@v5
    - uses: pre-commit/action@v3.0.1
